### ISSUE TITLE
cannot run 

### ISSUE THREAD

**Issue by willin** [kadira-samples/react-graphql-todos#2]
```

WARNING in ./~/encoding/lib/iconv-loader.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/encoding/lib/iconv-loader.js 9:12-34

ERROR in ./~/iconv-lite/encodings/tables/gb18030-ranges.json
Module parse failed: /Users/willin/Desktop/react-graphql-todos/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/willin/Desktop/react-graphql-todos/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/iconv-lite/encodings/dbcs-data.js 106:37-76
webpack: Failed to compile.
```

**Comment by davidmroth** [comment]
I believe this has been resolved with this [patch](https://github.com/kadira-samples/react-graphql-todos/pull/3)
